# Copyright 2026 Rover A1 contributors
# Licensed under the Apache License, Version 2.0.

import os
import struct
import sys
import zlib

import pytest

HERE = os.path.dirname(__file__)
sys.path.insert(0, os.path.join(HERE, '..', 'scripts'))
sys.path.insert(0, HERE)

from rover_map_import import import_site  # noqa: E402
from site_io import (  # noqa: E402
    CHARGER, DirMapSource, LANE, MapSourceError, render_preview, SshMapSource, WAYPOINT,
    write_site)
from test_rover_map_import import PLACES, write_map  # noqa: E402
import yaml  # noqa: E402


@pytest.fixture
def maps(tmp_path):
    """A /maps-like directory: 'lab' (5 places), 'bare' (map, no places), and 'active'."""
    root = tmp_path / 'maps'
    (root / 'lab').mkdir(parents=True)
    write_map(root / 'lab')
    (root / 'bare').mkdir()
    write_map(root / 'bare')
    os.remove(root / 'bare' / 'places.yaml')
    (root / 'active').write_text('lab\n')
    return root


# A stand-in for ssh: runs the remote script locally, with the test's maps dir as the rover's.
FAKE_SSH = """#!/bin/bash
if [ "$FAKE_SSH_FAIL" = denied ]; then
    echo "root@rover: Permission denied (password)." >&2; exit 255
fi
if [ "$FAKE_SSH_FAIL" = host_changed ]; then
    echo "@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @" >&2
    echo "Host key verification failed." >&2; exit 255
fi
script="${{@: -1}}"
exec bash -c "$script"
"""


@pytest.fixture
def fake_ssh(tmp_path):
    path = tmp_path / 'fake_ssh'
    path.write_text(FAKE_SSH.format())
    path.chmod(0o755)
    return str(path)


def test_dir_source_lists_maps_places_and_the_active_one(maps):
    listing = DirMapSource(str(maps)).list_maps()
    assert [m['name'] for m in listing] == ['bare', 'lab']
    lab = listing[1]
    assert lab['has_map'] and lab['active'] and lab['modified'] > 0
    assert sorted(lab['places']) == sorted(PLACES)
    assert listing[0]['places'] == [] and not listing[0]['active']


def test_dir_source_fetch_and_missing_map(maps, tmp_path):
    source = DirMapSource(str(maps))
    target = source.fetch('lab', str(tmp_path / 'out'))
    assert sorted(os.listdir(target)) == ['map.pgm', 'map.yaml', 'places.yaml']
    with pytest.raises(MapSourceError, match="no map named 'nope'.*bare, lab"):
        source.fetch('nope', str(tmp_path / 'out2'))


def test_ssh_source_lists_and_fetches_in_one_connection_each(maps, tmp_path, fake_ssh):
    source = SshMapSource('root@rover', remote_dir=str(maps), ssh=(fake_ssh,))
    assert source.list_maps() == DirMapSource(str(maps)).list_maps()
    target = source.fetch('lab', str(tmp_path / 'out'))
    assert sorted(os.listdir(target)) == ['map.pgm', 'map.yaml', 'places.yaml']
    assert import_site('lab', target, 'dock', clearance=0.3).waypoints


def test_ssh_source_errors_name_the_problem(maps, tmp_path, fake_ssh, monkeypatch):
    source = SshMapSource('root@rover', remote_dir=str(maps), ssh=(fake_ssh,))
    with pytest.raises(MapSourceError, match="no map named 'nope'.*maps on the rover: bare lab"):
        source.fetch('nope', str(tmp_path / 'a'))
    os.remove(maps / 'bare' / 'map.pgm')
    with pytest.raises(MapSourceError, match='has no map.yaml/map.pgm'):
        source.fetch('bare', str(tmp_path / 'b'))
    assert SshMapSource('root@rover', remote_dir=str(tmp_path / 'nothing'),
                        ssh=(fake_ssh,)).check() == ('ok', '')


def test_ssh_check_tells_a_missing_key_from_an_unreachable_rover(fake_ssh, monkeypatch):
    monkeypatch.setenv('FAKE_SSH_FAIL', 'denied')
    state, detail = SshMapSource('root@rover', ssh=(fake_ssh,)).check()
    assert state == 'needs_key' and 'Permission denied' in detail
    monkeypatch.setenv('FAKE_SSH_FAIL', 'host_changed')
    assert SshMapSource('root@rover', ssh=(fake_ssh,)).check()[0] == 'needs_key'
    state, _ = SshMapSource('root@rover', ssh=('/bin/false',)).check()
    assert state == 'unreachable'


def test_write_site_writes_floor_plan_building_and_fleet_config(maps, tmp_path):
    site = import_site('lab', str(maps / 'lab'), 'dock', clearance=0.3)
    template = {
        'rmf_fleet': {'name': 'rover_fleet', 'robots': {'rover_a1': {'charger': 'x'}},
                      'transforms': {}},
        'vda5050': {'map_name': 'rover_world', 'broker': {'host': 'mosquitto', 'port': 1883}},
    }
    out, config_path = tmp_path / 'site', tmp_path / 'site' / 'fleet_lab.yaml'
    charger = write_site(site, str(out), str(config_path), template, '192.168.1.201', 1883,
                         origin='a test')
    assert charger == 'dock'
    assert sorted(os.listdir(out)) == ['fleet_lab.yaml', 'lab.building.yaml', 'lab.png']
    text = config_path.read_text()
    assert text.startswith('# Generated by a test')
    config = yaml.safe_load(text)
    assert config['vda5050']['broker']['host'] == '192.168.1.201'
    assert list(config['rmf_fleet']['transforms']) == ['lab']


def read_rgb_png(path):
    """(width, height, rows of (r, g, b)) for the 8-bit RGB PNGs write_png makes."""
    data = open(path, 'rb').read()
    assert data[:8] == b'\x89PNG\r\n\x1a\n'
    width, height, depth, colour = struct.unpack('>IIBB', data[16:26])
    assert (depth, colour) == (8, 2)
    idat, pos = b'', 8
    while pos < len(data):
        length, kind = struct.unpack('>I4s', data[pos:pos + 8])
        if kind == b'IDAT':
            idat += data[pos + 8:pos + 8 + length]
        pos += 12 + length
    raw = zlib.decompress(idat)
    stride = 1 + 3 * width
    rows = []
    for r in range(height):
        line = raw[r * stride + 1:(r + 1) * stride]
        rows.append([tuple(line[3 * c:3 * c + 3]) for c in range(width)])
    return width, height, rows


def test_preview_draws_lanes_places_and_the_charger(maps, tmp_path):
    site = import_site('lab', str(maps / 'lab'), 'dock', clearance=0.3)
    path = str(tmp_path / 'preview.png')
    render_preview(site, path, crop=False)
    width, height, rows = read_rgb_png(path)
    assert (width, height) == (site.width, site.height)
    colours = {c for row in rows for c in row}
    assert {LANE, WAYPOINT, CHARGER} <= colours
    dock = next(w for w in site.waypoints if w.name == 'dock')
    assert rows[int(dock.py)][int(dock.px)] == CHARGER
