# Copyright 2026 Rover A1 contributors
# Licensed under the Apache License, Version 2.0.

"""
Turn a map saved on the rover (rover_indoor_nav_manager: /maps/<name>/map.yaml, map.pgm,
places.yaml) into an RMF site: floor plan, building with one waypoint per place, and lanes.

Coordinates. map_server's image has its bottom-left corner at the map origin (ox, oy), with
resolution r and H rows. The floor plan is that same image, so with building_writer's pixel ->
RMF convention

    robot (x, y) = RMF (x, y) + (ox, oy + H * r)

exactly: the fleet config's transform comes from map.yaml, nothing is surveyed.

Lanes. Two places are joined when the straight segment between them keeps `clearance` metres
from every occupied or unknown cell (a chamfer distance transform of the grid), and is no longer
than `max_lane`. Of those candidates the importer keeps a minimum spanning tree (so the graph is
connected whenever it can be) plus each place's `neighbours` shortest edges. Sparse on purpose:
the rover stops at every RMF waypoint.

Pure Python + PyYAML, so it runs on the host and in tests without ROS or RMF.
"""

from dataclasses import dataclass, field
import math
import os
from typing import Dict, List, Sequence, Tuple

from building_writer import building_yaml, Waypoint
import yaml

FREE, OCCUPIED, UNKNOWN = 0, 1, 2
SHADES = {FREE: 250, OCCUPIED: 70, UNKNOWN: 205}


class MapImportError(ValueError):
    """The map or its places cannot become an RMF site; the message says why."""


@dataclass(frozen=True)
class MapMeta:
    image: str
    resolution: float
    origin: Tuple[float, float, float]
    negate: bool = False
    # nav2 map_saver writes these for trinary maps: 254 free, 0 occupied, 205 unknown
    # (205 -> 0.19608, just above free_thresh).
    occupied_thresh: float = 0.65
    free_thresh: float = 0.196


@dataclass(frozen=True)
class Place:
    name: str
    x: float
    y: float


@dataclass
class Site:
    name: str
    width: int
    height: int
    resolution: float
    translation: Tuple[float, float]
    floor_plan: List[List[int]]
    waypoints: List[Waypoint]
    lanes: List[Tuple[str, str]]
    warnings: List[str] = field(default_factory=list)

    def building(self) -> str:
        return building_yaml(
            building=self.name, level=self.name, image_name=f'{self.name}.png',
            image_width_px=self.width, image_width_m=round(self.width * self.resolution, 6),
            waypoints=self.waypoints, lanes=self.lanes,
            comments=[f'Generated by scripts/import_rover_map.py from rover map {self.name!r}.',
                      'Re-run the importer after changing the map or its places.'])


# --- reading ----------------------------------------------------------------------------------

def load_map_yaml(path: str) -> MapMeta:
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    try:
        origin = tuple(float(v) for v in data['origin'])
        meta = MapMeta(
            image=str(data['image']),
            resolution=float(data['resolution']),
            origin=(origin + (0.0, 0.0, 0.0))[:3],
            negate=bool(int(data.get('negate', 0))),
            occupied_thresh=float(data.get('occupied_thresh', 0.65)),
            free_thresh=float(data.get('free_thresh', 0.196)))
    except (KeyError, TypeError, ValueError) as e:
        raise MapImportError(f'{path}: not a map_server map yaml ({e})')
    if abs(meta.origin[2]) > 1e-6:
        raise MapImportError(
            f'{path}: origin yaw {meta.origin[2]} is not 0 (map_saver writes 0); '
            'rotated maps are not supported')
    if meta.resolution <= 0:
        raise MapImportError(f'{path}: resolution must be > 0')
    return meta


def read_pgm(path: str) -> Tuple[int, int, List[List[int]]]:
    """Binary (P5) 8-bit PGM -> (width, height, rows); row 0 is the top of the map."""
    with open(path, 'rb') as f:
        data = f.read()
    tokens, pos = [], 0
    while len(tokens) < 4:
        while pos < len(data) and data[pos:pos + 1].isspace():
            pos += 1
        if data[pos:pos + 1] == b'#':
            pos = data.index(b'\n', pos) + 1
            continue
        start = pos
        while pos < len(data) and not data[pos:pos + 1].isspace():
            pos += 1
        tokens.append(data[start:pos])
    pos += 1  # the single whitespace after maxval
    if tokens[0] != b'P5':
        raise MapImportError(f'{path}: not a binary PGM (P5)')
    width, height, maxval = (int(t) for t in tokens[1:])
    if maxval > 255:
        raise MapImportError(f'{path}: 16-bit PGM not supported')
    pixels = data[pos:pos + width * height]
    if len(pixels) != width * height:
        raise MapImportError(f'{path}: truncated image')
    rows = [list(pixels[r * width:(r + 1) * width]) for r in range(height)]
    return width, height, rows


def load_places(path: str) -> List[Place]:
    if not os.path.exists(path):
        return []
    with open(path) as f:
        data = yaml.safe_load(f) or {}
    places = []
    for p in data.get('places') or []:
        try:
            places.append(Place(str(p['name']).strip(), float(p['x']), float(p['y'])))
        except (KeyError, TypeError, ValueError) as e:
            raise MapImportError(f'{path}: bad place {p!r} ({e})')
    return places


# --- grid ------------------------------------------------------------------------------------

def classify(rows: Sequence[Sequence[int]], meta: MapMeta) -> List[List[int]]:
    """nav2 map_io's trinary interpretation of each pixel (>= occupied, <= free)."""
    table = []
    for value in range(256):
        occ = value / 255.0 if meta.negate else (255 - value) / 255.0
        table.append(OCCUPIED if occ >= meta.occupied_thresh
                     else FREE if occ <= meta.free_thresh else UNKNOWN)
    return [[table[v] for v in row] for row in rows]


def floor_plan(grid: Sequence[Sequence[int]]) -> List[List[int]]:
    return [[SHADES[c] for c in row] for row in grid]


def distance_to_blocked(grid: Sequence[Sequence[int]]) -> List[List[float]]:
    """Chamfer (1, sqrt 2) distance in cells from each cell to the nearest non-free cell."""
    h, w = len(grid), len(grid[0])
    big = float(h + w)
    diag = math.sqrt(2.0)
    d = [[0.0 if c != FREE else big for c in row] for row in grid]
    for r in range(h):
        row, up = d[r], d[r - 1] if r else None
        for c in range(w):
            v = row[c]
            if v == 0.0:
                continue
            if c:
                v = min(v, row[c - 1] + 1.0)
            if up is not None:
                v = min(v, up[c] + 1.0)
                if c:
                    v = min(v, up[c - 1] + diag)
                if c + 1 < w:
                    v = min(v, up[c + 1] + diag)
            row[c] = v
    for r in range(h - 1, -1, -1):
        row, down = d[r], d[r + 1] if r + 1 < h else None
        for c in range(w - 1, -1, -1):
            v = row[c]
            if v == 0.0:
                continue
            if c + 1 < w:
                v = min(v, row[c + 1] + 1.0)
            if down is not None:
                v = min(v, down[c] + 1.0)
                if c + 1 < w:
                    v = min(v, down[c + 1] + diag)
                if c:
                    v = min(v, down[c - 1] + diag)
            row[c] = v
    return d


def clearance_at(dist: Sequence[Sequence[float]], px: float, py: float) -> float:
    """Distance in cells at a pixel position; 0 outside the map."""
    col, row = int(px), int(py)
    if 0 <= row < len(dist) and 0 <= col < len(dist[0]):
        return dist[row][col]
    return 0.0


def segment_is_clear(dist, a: Tuple[float, float], b: Tuple[float, float],
                     clearance_cells: float) -> bool:
    """
    Whether a lane a-b keeps clearance_cells from anything blocked, sampled every half cell.

    Within clearance_cells of either end the lane only has to stay out of blocked cells: places
    next to a wall (a dock) stay reachable, Nav 2 does the last bit, and a lane still cannot
    pass through a wall, whose cells are blocked.
    """
    length = math.hypot(b[0] - a[0], b[1] - a[1])
    steps = max(1, int(length * 2))
    for i in range(steps + 1):
        t = i / steps
        room = clearance_at(dist, a[0] + (b[0] - a[0]) * t, a[1] + (b[1] - a[1]) * t)
        near_end = min(t, 1 - t) * length < clearance_cells
        if room < (1.0 if near_end else clearance_cells):
            return False
    return True


# --- lanes ------------------------------------------------------------------------------------

def plan_lanes(points: Dict[str, Tuple[float, float]], dist, clearance_cells: float,
               max_lane_cells: float, neighbours: int) -> List[Tuple[str, str]]:
    names = list(points)
    candidates = []
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            length = math.hypot(points[a][0] - points[b][0], points[a][1] - points[b][1])
            if length <= max_lane_cells and \
                    segment_is_clear(dist, points[a], points[b], clearance_cells):
                candidates.append((length, a, b))
    candidates.sort()

    # Minimum spanning tree (Kruskal) keeps the graph connected with the shortest lanes.
    parent = {n: n for n in names}

    def root(n):
        while parent[n] != n:
            parent[n] = parent[parent[n]]
            n = parent[n]
        return n

    chosen = set()
    for _, a, b in candidates:
        ra, rb = root(a), root(b)
        if ra != rb:
            parent[ra] = rb
            chosen.add((a, b))
    components: Dict[str, List[str]] = {}
    for n in names:
        components.setdefault(root(n), []).append(n)
    if len(components) > 1:
        groups = '; '.join(', '.join(sorted(c)) for c in components.values())
        raise MapImportError(
            f'the places cannot all be joined by clear straight lanes: {groups}. Add places '
            'where corridors meet, or relax --clearance / --max-lane')

    # Plus each place's shortest lanes, for alternative routes.
    for n in names:
        mine = [(length, a, b) for length, a, b in candidates if n in (a, b)]
        for _, a, b in mine[:neighbours]:
            chosen.add((a, b))
    return sorted(chosen, key=lambda e: (names.index(e[0]), names.index(e[1])))


# --- the whole import --------------------------------------------------------------------------

def import_site(name: str, map_dir: str, charger: str, clearance: float = 0.8,
                max_lane: float = 15.0, neighbours: int = 3) -> Site:
    meta = load_map_yaml(os.path.join(map_dir, 'map.yaml'))
    image = meta.image if os.path.isabs(meta.image) else os.path.join(map_dir, meta.image)
    if not os.path.exists(image):
        image = os.path.join(map_dir, os.path.basename(meta.image))
    width, height, rows = read_pgm(image)
    grid = classify(rows, meta)
    places = load_places(os.path.join(map_dir, 'places.yaml'))
    if len(places) < 2:
        raise MapImportError(
            f'{map_dir}: {len(places)} place(s); save at least two in the drive UI '
            f'(one of them {charger!r}, where the rover parks)')
    by_name = {p.name.lower(): p for p in places}
    if len(by_name) != len(places):
        raise MapImportError(f'{map_dir}: place names differ only in case')
    if charger.lower() not in by_name:
        raise MapImportError(
            f'no place named {charger!r} for the charger/parking spot; places: '
            + ', '.join(p.name for p in places))
    charger_name = by_name[charger.lower()].name

    r = meta.resolution
    ox, oy = meta.origin[0], meta.origin[1]
    dist = distance_to_blocked(grid)
    clearance_cells = clearance / r
    warnings = []
    points, waypoints = {}, []
    for p in places:
        px, py = (p.x - ox) / r, height - (p.y - oy) / r
        if not (0 <= px < width and 0 <= py < height):
            raise MapImportError(f'place {p.name!r} ({p.x:.2f}, {p.y:.2f}) is outside the map')
        room = clearance_at(dist, px, py) * r
        if room < clearance:
            warnings.append(f'place {p.name!r} is {room:.2f} m from an obstacle or unknown '
                            f'area (< {clearance} m): the rover may not fit there')
        points[p.name] = (px, py)
        waypoints.append(Waypoint(p.name, px, py, charger=p.name == charger_name))

    lanes = plan_lanes(points, dist, clearance_cells, max_lane / r, neighbours)
    return Site(name=name, width=width, height=height, resolution=r,
                translation=(round(ox, 6), round(oy + height * r, 6)),
                floor_plan=floor_plan(grid), waypoints=waypoints, lanes=lanes,
                warnings=warnings)


def fleet_config(template: dict, site: Site, charger: str, broker_host: str,
                 broker_port: int) -> dict:
    """The fleet config for a site: the template with the site's map, transform and broker."""
    config = yaml.safe_load(yaml.safe_dump(template))  # deep copy
    fleet = config['rmf_fleet']
    fleet['transforms'] = {site.name: {'rotation': 0.0, 'scale': 1.0,
                                       'translation': list(site.translation)}}
    for robot in fleet['robots'].values():
        robot['charger'] = charger
    vda = config['vda5050']
    vda['map_name'] = site.name
    vda['broker']['host'] = broker_host
    vda['broker']['port'] = broker_port
    return config
