#!/usr/bin/env python3
# Copyright 2026 Rover A1 contributors
# Licensed under the Apache License, Version 2.0.

from rover_rmf_fleet_adapter.presentation.fleet_adapter import main

if __name__ == '__main__':
    main()
