#!/bin/bash
# Copyright 2026 Mechatronics Academy
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# The RMF stack on the WireGuard server (docker-compose.server.yml).
#
#   rmf-server.sh init                 generate server/.env and the broker logins (once)
#   rmf-server.sh rover-password       print the rover_a1 broker password (for balena)
#   rmf-server.sh <compose args...>    e.g. up -d --build | ps | logs -f rmf | down
#
# server/ holds the secrets and is not tracked by git.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SERVER="$HERE/server"
ENV_FILE="$SERVER/.env"
MOSQUITTO_IMAGE=docker.io/library/eclipse-mosquitto:2

compose() {
    docker compose -f "$HERE/docker-compose.yml" -f "$HERE/docker-compose.server.yml" \
        --env-file "$ENV_FILE" "$@"
}

init() {
    mkdir -p "$SERVER"
    chmod 700 "$SERVER"
    if [ -s "$ENV_FILE" ] && [ "${1:-}" != --force ]; then
        echo "$ENV_FILE exists; 'init --force' regenerates both broker passwords" >&2
        exit 1
    fi
    local rmf_pw rover_pw
    rmf_pw="$(openssl rand -hex 16)"
    rover_pw="$(openssl rand -hex 16)"
    umask 077
    cat > "$ENV_FILE" <<EOF
# Generated by rmf-server.sh init. Secrets: do not commit.
RMF_BIND_IP=10.8.0.1
RMF_MQTT_PASSWORD=$rmf_pw
ROVER_MQTT_PASSWORD=$rover_pw
EOF
    # mosquitto runs as uid 1883 and wants its password file private.
    docker run --rm -e RMF_PW="$rmf_pw" -e ROVER_PW="$rover_pw" -v "$SERVER:/out" \
        "$MOSQUITTO_IMAGE" sh -c '
            rm -f /out/mosquitto.passwd
            mosquitto_passwd -b -c /out/mosquitto.passwd rmf "$RMF_PW"
            mosquitto_passwd -b /out/mosquitto.passwd rover_a1 "$ROVER_PW"
            chown 1883:1883 /out/mosquitto.passwd
            chmod 0700 /out/mosquitto.passwd'
    echo "Wrote $ENV_FILE and the broker logins rmf, rover_a1."
}

case "${1:-}" in
    init) shift; init "$@" ;;
    rover-password) sed -n 's/^ROVER_MQTT_PASSWORD=//p' "$ENV_FILE" ;;
    "") sed -n '2,8s/^# \{0,1\}//p' "$0"; exit 1 ;;
    *) compose "$@" ;;
esac
